# Stage 1 — Build
FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_OPTIONS="--max-old-space-size=768"

# NEXT_PUBLIC_* are inlined into the client bundle at build time (not at container runtime).
ARG NEXT_PUBLIC_ALCHEMY_KEY
ARG NEXT_PUBLIC_CHARITY_CORE_ADDRESS
ARG NEXT_PUBLIC_DONATION_VAULT_ADDRESS
ARG NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS
ARG NEXT_PUBLIC_IMPACT_NFT_ADDRESS
ARG NEXT_PUBLIC_USDC_ADDRESS
ENV NEXT_PUBLIC_ALCHEMY_KEY=$NEXT_PUBLIC_ALCHEMY_KEY
ENV NEXT_PUBLIC_CHARITY_CORE_ADDRESS=$NEXT_PUBLIC_CHARITY_CORE_ADDRESS
ENV NEXT_PUBLIC_DONATION_VAULT_ADDRESS=$NEXT_PUBLIC_DONATION_VAULT_ADDRESS
ENV NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS=$NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS
ENV NEXT_PUBLIC_IMPACT_NFT_ADDRESS=$NEXT_PUBLIC_IMPACT_NFT_ADDRESS
ENV NEXT_PUBLIC_USDC_ADDRESS=$NEXT_PUBLIC_USDC_ADDRESS

COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

# Stage 2 — Production
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
