// Contract addresses — populated after Sepolia deploy
export const ADDRESSES = {
  charityCore:   process.env.NEXT_PUBLIC_CHARITY_CORE_ADDRESS   as `0x${string}`,
  donationVault: process.env.NEXT_PUBLIC_DONATION_VAULT_ADDRESS as `0x${string}`,
  governanceDAO: process.env.NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS as `0x${string}`,
  impactNFT:     process.env.NEXT_PUBLIC_IMPACT_NFT_ADDRESS     as `0x${string}`,
} as const;

// Minimal ABIs — full ABIs generated by Hardhat post-deploy
export const CHARITY_CORE_ABI = [
  "function createCampaign(string,uint256,uint256,uint8) payable returns (uint256)",
  "function getCampaign(uint256) view returns (tuple(uint256,address,string,uint256,uint256,uint256,uint8,uint8,uint8))",
  "function getCampaignsByOrg(address) view returns (uint256[])",
  "function totalCampaigns() view returns (uint256)",
  "function isOrgVerified(address) view returns (bool)",
  "event CampaignCreated(uint256 indexed,address indexed,uint256,uint256)",
] as const;

export const DONATION_VAULT_ABI = [
  "function donate(uint256) payable",
  "function submitMilestoneProof(uint256,uint8,string)",
  "function claimRefund(uint256)",
  "function getDonorAmount(uint256,address) view returns (uint256)",
  "function getCampaignEscrowBalance(uint256) view returns (uint256)",
  "function getMilestone(uint256,uint8) view returns (tuple(string,uint256,bool,uint256))",
  "event DonationReceived(uint256 indexed,address indexed,uint256)",
  "event FundsReleased(uint256 indexed,uint8,uint256,address)",
  "event RefundProcessed(uint256 indexed,address indexed,uint256)",
] as const;

export const GOVERNANCE_DAO_ABI = [
  "function castVote(uint256,uint8)",
  "function queueProposal(uint256)",
  "function executeProposal(uint256)",
  "function getProposal(uint256) view returns (tuple(uint256,uint256,uint8,string,address,uint256,uint256,uint256,uint256,uint256,uint256,uint8,uint256))",
  "function getProposalState(uint256) view returns (uint8)",
  "function hasVoted(uint256,address) view returns (bool)",
  "function getVotingPower(uint256,address) view returns (uint256)",
  "event VoteCast(uint256 indexed,address indexed,uint8,uint256)",
] as const;

export const IMPACT_NFT_ABI = [
  "function getDonorNFTs(address) view returns (uint256[])",
  "function getNFTMetadata(uint256) view returns (tuple(uint256,address,uint8,uint256,uint256,bool,string))",
  "function hasMintedForCampaign(address,uint256) view returns (bool)",
  "event ImpactNFTMinted(uint256 indexed,address indexed,uint256 indexed,uint8)",
] as const;
