// Contract addresses — populated after Sepolia deploy
export const ADDRESSES = {
  charityCore:   process.env.NEXT_PUBLIC_CHARITY_CORE_ADDRESS   as `0x${string}`,
  donationVault: process.env.NEXT_PUBLIC_DONATION_VAULT_ADDRESS as `0x${string}`,
  governanceDAO: process.env.NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS as `0x${string}`,
  impactNFT:     process.env.NEXT_PUBLIC_IMPACT_NFT_ADDRESS     as `0x${string}`,
} as const;

// Minimal ABIs — full ABIs generated by Hardhat post-deploy
export const CHARITY_CORE_ABI = [
  // Functions
  "function createCampaign(string,uint256,uint256,uint8,uint8,string) payable returns (uint256)",
  "function getCampaign(uint256) view returns (tuple(uint256,address,string,uint256,uint256,uint256,uint8,uint8,uint8,uint8,string,uint256,uint256))",
  "function getCharityProgress(uint256) view returns (uint256,uint256,uint256,uint256,bool,uint256)",
  "function getCharities(uint256,uint256) view returns (tuple(uint256,address,string,uint256,uint256,uint256,uint8,uint8,uint8,uint8,string,uint256,uint256)[])",
  "function cancelCampaign(uint256)",
  "function finalizeCampaign(uint256)",
  "function extendDeadline(uint256,uint256)",
  "function isOrgVerified(address) view returns (bool)",
  "function totalCampaigns() view returns (uint256)",
  "function getCampaignsByOrg(address) view returns (uint256[])",
  
  // Events
  "event CampaignCreated(uint256 indexed,address indexed,uint256,uint256)",
  "event CampaignCancelled(uint256 indexed,address indexed,uint256)",
  "event CampaignFinalized(uint256 indexed,uint8)",
] as const;

export const DONATION_VAULT_ABI = [
  { name: "donate", type: "function", stateMutability: "payable", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [] },
  { name: "donateUSDC", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "submitMilestoneProof", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }, { name: "milestoneIndex", type: "uint8" }, { name: "proofCID", type: "string" }], outputs: [] },
  { name: "claimRefund", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [] },
  { name: "canRefund", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }], outputs: [{ name: "eligible", type: "bool" }, { name: "amount", type: "uint256" }, { name: "refundDeadline", type: "uint256" }] },
  { name: "getDonorInfo", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }], outputs: [{ name: "", type: "tuple", components: [{ name: "totalDonated", type: "uint256" }, { name: "donationCount", type: "uint256" }, { name: "lastDonatedAt", type: "uint256" }] }] },
  { name: "getDonorAmount", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "getCharityDonors", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "address[]" }] },
  { name: "getCampaignEscrowBalance", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "getMilestone", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "milestoneIndex", type: "uint8" }], outputs: [{ name: "", type: "tuple", components: [{ name: "proofCID", type: "string" }, { name: "releaseAmount", type: "uint256" }, { name: "released", type: "bool" }, { name: "proposalId", type: "uint256" }] }] },
  { name: "DonationReceived", type: "event", inputs: [{ name: "campaignId", type: "uint256", indexed: true }, { name: "donor", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }, { name: "tokenType", type: "uint8", indexed: false }] },
] as const;

export const GOVERNANCE_DAO_ABI = [
  // Functions
  "function castVote(uint256,uint8)",
  "function getCampaignProposals(uint256) view returns (uint256[])",
  "function queueProposal(uint256)",
  "function executeProposal(uint256)",
  "function getProposal(uint256) view returns (tuple(uint256,uint256,uint8,string,address,uint256,uint256,uint256,uint256,uint256,uint256,uint8,uint256,uint256))",
  "function getProposalState(uint256) view returns (uint8)",
  "function getActiveProposal(uint256) view returns (uint256)",
  "function hasVoted(uint256,address) view returns (bool)",
  "function getVotingPower(uint256,address) view returns (uint256)",
  "function resubmitProposal(uint256) returns (uint256)",
  
  // Events
  "event VoteCast(uint256 indexed,address indexed,uint8,uint256)",
] as const;

export const IMPACT_NFT_ABI = [
  // Functions
  "function getCampaignNFTs(uint256) view returns (uint256[])",
  "function getDonorNFTs(address) view returns (uint256[])",
  "function getNFTMetadata(uint256) view returns (tuple(uint256,address,uint8,uint256,uint256,bool,string,uint8))",
  "function hasMintedForCampaign(address,uint256) view returns (bool)",
  "function upgradeTier(uint256)",
  
  // Events
  "event ImpactNFTMinted(uint256 indexed,address indexed,uint256 indexed,uint8)",
] as const;
