// Contract addresses — populated after Sepolia deploy
export const ADDRESSES = {
  charityCore:   process.env.NEXT_PUBLIC_CHARITY_CORE_ADDRESS   as `0x${string}`,
  donationVault: process.env.NEXT_PUBLIC_DONATION_VAULT_ADDRESS as `0x${string}`,
  governanceDAO: process.env.NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS as `0x${string}`,
  impactNFT:     process.env.NEXT_PUBLIC_IMPACT_NFT_ADDRESS     as `0x${string}`,
} as const;

// Minimal ABIs — full ABIs generated by Hardhat post-deploy
export const CHARITY_CORE_ABI = [
  // Functions
  "function createCampaign(string,uint256,uint256,uint8,uint8,string) payable returns (uint256)",
  "function getCampaign(uint256) view returns (tuple(uint256,address,string,uint256,uint256,uint256,uint8,uint8,uint8,uint8,string,uint256,uint256))",
  "function getCharityProgress(uint256) view returns (uint256,uint256,uint256,uint256,bool,uint256)",
  "function getCharities(uint256,uint256) view returns (tuple(uint256,address,string,uint256,uint256,uint256,uint8,uint8,uint8,uint8,string,uint256,uint256)[])",
  "function cancelCampaign(uint256)",
  "function finalizeCampaign(uint256)",
  "function extendDeadline(uint256,uint256)",
  "function isOrgVerified(address) view returns (bool)",
  "function totalCampaigns() view returns (uint256)",
  "function getCampaignsByOrg(address) view returns (uint256[])",
  
  // Events
  "event CampaignCreated(uint256 indexed,address indexed,uint256,uint256)",
  "event CampaignCancelled(uint256 indexed,address indexed,uint256)",
  "event CampaignFinalized(uint256 indexed,uint8)",
] as const;

export const DONATION_VAULT_ABI = [
  // Functions
  "function donate(uint256) payable",
  "function donateUSDC(uint256,uint256)",
  "function submitMilestoneProof(uint256,uint8,string)",
  "function canRefund(uint256,address) view returns (bool,uint256,uint256)",
  "function claimRefund(uint256)",
  "function getDonorInfo(uint256,address) view returns (tuple(uint256,uint256,uint256))",
  "function getDonorAmount(uint256,address) view returns (uint256)",
  "function getCharityDonors(uint256) view returns (address[])",
  "function getCampaignEscrowBalance(uint256) view returns (uint256)",
  "function getMilestone(uint256,uint8) view returns (tuple(string,uint256,bool,uint256))",
  
  // Events
  "event DonationReceived(uint256 indexed,address indexed,uint256,uint8)",
  "event FundsReleased(uint256 indexed,uint8,uint256,address)",
  "event RefundProcessed(uint256 indexed,address indexed,uint256)",
] as const;

export const GOVERNANCE_DAO_ABI = [
  // Functions
  "function castVote(uint256,uint8)",
  "function getCampaignProposals(uint256) view returns (uint256[])",
  "function queueProposal(uint256)",
  "function executeProposal(uint256)",
  "function getProposal(uint256) view returns (tuple(uint256,uint256,uint8,string,address,uint256,uint256,uint256,uint256,uint256,uint256,uint8,uint256,uint256))",
  "function getProposalState(uint256) view returns (uint8)",
  "function getActiveProposal(uint256) view returns (uint256)",
  "function hasVoted(uint256,address) view returns (bool)",
  "function getVotingPower(uint256,address) view returns (uint256)",
  "function resubmitProposal(uint256) returns (uint256)",
  
  // Events
  "event VoteCast(uint256 indexed,address indexed,uint8,uint256)",
] as const;

export const IMPACT_NFT_ABI = [
  // Functions
  "function getCampaignNFTs(uint256) view returns (uint256[])",
  "function getDonorNFTs(address) view returns (uint256[])",
  "function getNFTMetadata(uint256) view returns (tuple(uint256,address,uint8,uint256,uint256,bool,string,uint8))",
  "function hasMintedForCampaign(address,uint256) view returns (bool)",
  "function upgradeTier(uint256)",
  
  // Events
  "event ImpactNFTMinted(uint256 indexed,address indexed,uint256 indexed,uint8)",
] as const;
