// Contract addresses — prefer env, fallback to known Sepolia deploy.
// This prevents production builds from silently breaking if NEXT_PUBLIC_* vars are missing.
const FALLBACK_SEPOLIA_ADDRESSES = {
  charityCore:   "0x6fEEF9276B2215F0d41a0c7515Ea6718099552d4",
  donationVault: "0x016377C129f1d7B0Abbda97B8676D273F419cBAb",
  governanceDAO: "0x558e7811ae467f82A60E5c6FEa7aaeAae61f2c44",
  impactNFT:     "0x6B6e671EfB7fbEaBF41a7cCC4683F3683c88e5fd",
} as const;

export const ADDRESSES = {
  charityCore:
    (process.env.NEXT_PUBLIC_CHARITY_CORE_ADDRESS ||
      FALLBACK_SEPOLIA_ADDRESSES.charityCore) as `0x${string}`,
  donationVault:
    (process.env.NEXT_PUBLIC_DONATION_VAULT_ADDRESS ||
      FALLBACK_SEPOLIA_ADDRESSES.donationVault) as `0x${string}`,
  governanceDAO:
    (process.env.NEXT_PUBLIC_GOVERNANCE_DAO_ADDRESS ||
      FALLBACK_SEPOLIA_ADDRESSES.governanceDAO) as `0x${string}`,
  impactNFT:
    (process.env.NEXT_PUBLIC_IMPACT_NFT_ADDRESS ||
      FALLBACK_SEPOLIA_ADDRESSES.impactNFT) as `0x${string}`,
} as const;
 
// Minimal ABIs — full ABIs generated by Hardhat post-deploy
export const CHARITY_CORE_ABI = [
  { name: "createCampaign", type: "function", stateMutability: "payable", inputs: [{ name: "metadataCID", type: "string" }, { name: "goalAmount", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "totalMilestones", type: "uint8" }, { name: "paymentToken", type: "uint8" }, { name: "category", type: "string" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "getCampaign", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [{ name: "id", type: "uint256" }, { name: "orgAddress", type: "address" }, { name: "metadataCID", type: "string" }, { name: "goalAmount", type: "uint256" }, { name: "raisedAmount", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "status", type: "uint8" }, { name: "totalMilestones", type: "uint8" }, { name: "completedMilestones", type: "uint8" }, { name: "paymentToken", type: "uint8" }, { name: "category", type: "string" }, { name: "createdAt", type: "uint256" }, { name: "cancelledAt", type: "uint256" }] }] },
  { name: "getCharityProgress", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "raised", type: "uint256" }, { name: "goal", type: "uint256" }, { name: "progressBps", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "isExpired", type: "bool" }, { name: "timeLeft", type: "uint256" }] },
  { name: "cancelCampaign", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [] },
  { name: "finalizeCampaign", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [] },
  { name: "extendDeadline", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }, { name: "newDeadline", type: "uint256" }], outputs: [] },
  { name: "MAX_EXTENSION", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "isOrgVerified", type: "function", stateMutability: "view", inputs: [{ name: "org", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { name: "totalCampaigns", type: "function", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "getCampaignsByOrg", type: "function", stateMutability: "view", inputs: [{ name: "org", type: "address" }], outputs: [{ name: "", type: "uint256[]" }] },
  { name: "verifyOrg", type: "function", stateMutability: "nonpayable", inputs: [{ name: "org", type: "address" }], outputs: [] },
  { name: "revokeOrg", type: "function", stateMutability: "nonpayable", inputs: [{ name: "org", type: "address" }], outputs: [] },
  { name: "hasRole", type: "function", stateMutability: "view", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  // OZ AccessControl — needed for Verifier role management (Admin only)
  { name: "grantRole", type: "function", stateMutability: "nonpayable", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [] },
  { name: "revokeRole", type: "function", stateMutability: "nonpayable", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [] },
  // Events
  { name: "CampaignCreated", type: "event", inputs: [{ name: "campaignId", type: "uint256", indexed: true }, { name: "org", type: "address", indexed: true }, { name: "goal", type: "uint256", indexed: false }, { name: "deadline", type: "uint256", indexed: false }] },
  // Needed for getLogs in Admin Panel verified-orgs list
  { name: "OrgVerified", type: "event", inputs: [{ name: "org", type: "address", indexed: true }, { name: "verified", type: "bool", indexed: false }] },
] as const;
 
export const DONATION_VAULT_ABI = [
  { name: "donate", type: "function", stateMutability: "payable", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [] },
  { name: "donateUSDC", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }, { name: "amount", type: "uint256" }], outputs: [] },
  { name: "submitMilestoneProof", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }, { name: "milestoneIndex", type: "uint8" }, { name: "proofCID", type: "string" }], outputs: [] },
  { name: "claimRefund", type: "function", stateMutability: "nonpayable", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [] },
  { name: "canRefund", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }], outputs: [{ name: "eligible", type: "bool" }, { name: "amount", type: "uint256" }, { name: "refundDeadline", type: "uint256" }] },
  { name: "getDonorInfo", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }], outputs: [{ name: "", type: "tuple", components: [{ name: "totalDonated", type: "uint256" }, { name: "donationCount", type: "uint256" }, { name: "lastDonatedAt", type: "uint256" }] }] },
  { name: "getDonorAmount", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "getCharityDonors", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "address[]" }] },
  { name: "getCampaignEscrowBalance", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "getMilestone", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "milestoneIndex", type: "uint8" }], outputs: [{ name: "", type: "tuple", components: [{ name: "proofCID", type: "string" }, { name: "releaseAmount", type: "uint256" }, { name: "released", type: "bool" }, { name: "proposalId", type: "uint256" }] }] },
  { name: "DonationReceived", type: "event", inputs: [{ name: "campaignId", type: "uint256", indexed: true }, { name: "donor", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }, { name: "tokenType", type: "uint8", indexed: false }] },
] as const;
 
export const GOVERNANCE_DAO_ABI = [
  { name: "castVote", type: "function", stateMutability: "nonpayable", inputs: [{ name: "proposalId", type: "uint256" }, { name: "choice", type: "uint8" }], outputs: [] },
  { name: "getCampaignProposals", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "uint256[]" }] },
  { name: "queueProposal", type: "function", stateMutability: "nonpayable", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { name: "executeProposal", type: "function", stateMutability: "nonpayable", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { name: "resubmitProposal", type: "function", stateMutability: "nonpayable", inputs: [{ name: "oldProposalId", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "getProposal", type: "function", stateMutability: "view", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [{ name: "id", type: "uint256" }, { name: "campaignId", type: "uint256" }, { name: "milestoneIndex", type: "uint8" }, { name: "proofCID", type: "string" }, { name: "proposer", type: "address" }, { name: "startBlock", type: "uint256" }, { name: "endBlock", type: "uint256" }, { name: "forVotes", type: "uint256" }, { name: "againstVotes", type: "uint256" }, { name: "abstainVotes", type: "uint256" }, { name: "totalVotingPower", type: "uint256" }, { name: "state", type: "uint8" }, { name: "executeAfter", type: "uint256" }, { name: "snapshotBlock", type: "uint256" }] }] },
  { name: "getProposalState", type: "function", stateMutability: "view", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [{ name: "", type: "uint8" }] },
  { name: "getActiveProposal", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "hasVoted", type: "function", stateMutability: "view", inputs: [{ name: "proposalId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { name: "getVotingPower", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { name: "VoteCast", type: "event", inputs: [{ name: "proposalId", type: "uint256", indexed: true }, { name: "voter", type: "address", indexed: true }, { name: "choice", type: "uint8", indexed: false }, { name: "weight", type: "uint256", indexed: false }] },
] as const;
 
export const IMPACT_NFT_ABI = [
  { name: "getCampaignNFTs", type: "function", stateMutability: "view", inputs: [{ name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "uint256[]" }] },
  { name: "getDonorNFTs", type: "function", stateMutability: "view", inputs: [{ name: "donor", type: "address" }], outputs: [{ name: "", type: "uint256[]" }] },
  { name: "getNFTMetadata", type: "function", stateMutability: "view", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [{ name: "campaignId", type: "uint256" }, { name: "donor", type: "address" }, { name: "tier", type: "uint8" }, { name: "donatedAmount", type: "uint256" }, { name: "impactScore", type: "uint256" }, { name: "campaignCompleted", type: "bool" }, { name: "metadataCID", type: "string" }, { name: "paymentToken", type: "uint8" }] }] },
  { name: "hasMintedForCampaign", type: "function", stateMutability: "view", inputs: [{ name: "donor", type: "address" }, { name: "campaignId", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { name: "upgradeTier", type: "function", stateMutability: "nonpayable", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [] },
  { name: "ImpactNFTMinted", type: "event", inputs: [{ name: "tokenId", type: "uint256", indexed: true }, { name: "donor", type: "address", indexed: true }, { name: "campaignId", type: "uint256", indexed: true }, { name: "tier", type: "uint8", indexed: false }] },
] as const;